let arr=[5,7,8,9,4]
console.log(arr,typeof arr)
console.log(arr.length)
console.log(arr.push(3,1))
console.log(arr)
console.log(arr.pop())
console.log(arr)
console.log(arr.unshift(1,2))
console.log(arr)
console.log(arr.shift())
console.log(arr)
console.log(arr.sort())
console.log(arr)
console.log(arr.splice(2,2))
console.log(arr)
console.log(arr.splice(2,0,10))
console.log(arr)
console.log("Sharif".split('').reverse('').join(''))
